M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu22.04.1} date 2025-07-01T08:49:21+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-01T08:49:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X57.19Y-103.5
X62.97Y-103.5
M30
